services:
  - type: web
    name: django-stripe-store
    env: docker
    plan: starter
    autoDeploy: false
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: PORT
        value: "10000"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "1"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "1"
      - key: DJANGO_SECURE_HSTS_PRELOAD
        value: "1"
      - key: DJANGO_LOAD_DEMO_DATA
        value: "1"
      - key: DJANGO_CREATE_SUPERUSER
        value: "1"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY_USD
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY_USD
        sync: false
      - key: STRIPE_SECRET_KEY_EUR
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY_EUR
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
